#!/bin/zsh
set -e
cd /local/home/rikhil/vectordb/luceneutil
source .venv/bin/activate
export KNN_HEAP=16g KNN_INDEX_TYPE=ivfaster IVFASTER_FINE_TIER=afterburner4 \
  IVFASTER_COARSE_BITS=1 IVFASTER_COARSE_MF=1 \
  KNN_NDOC=1000000 KNN_NLIST=8000 IVFASTER_SPILL_MARGIN=1.40 IVFASTER_BRUTE_N=3000 \
  KNN_NPROBE=80 IVFASTER_VERIFY_MULT=2 IVFASTER_NPROBE_MARGIN=1.0 \
  IVFASTER_GRAPH_M=16 IVFASTER_EF_CONSTRUCTION=64 KNN_GCUT_AXES=1 IVFASTER_REPORT=1 \
  IVFASTER_MF_QUERY_CLIP_Q=0.95
python -u src/python/knnPerfTest.py 2>&1 | grep -iE "will now reindex|graphDescents=2000|^SUMMARY:" | tail -4
echo AB4DONE
